SETTINGS:
  DIRECTORY: '../IXI_dataset/IXI_downsampledx4_iacl_synthmorph/' 
  PROJECT_NAME: 'IXI_dataset'
  GPU_DEVICE: 0
  NUM_WORKERS: 48

DATASET:
  SUBJECT_ID: 'IXI002-Guys-0828' 
  LR_CONTRAST1: 'T1'  
  LR_CONTRAST2: 'T2' 
  
TRAINING:

  SEED: 12
  BATCH_SIZE: 131072 # 4000 #131072 #128*1024
  LR: 0.0004
  EPOCHS: 100
  OPTIM: 'Adam'
  SHUFFELING: True
  CONTRAST1_ONLY: False
  CONTRAST2_ONLY: False
  LOSS: 'MSELoss'
  LOSS_MSE_C1: 1.0
  LOSS_MSE_C2: 1.0

  # only one used at same time
  USE_MI: False
  USE_NMI: False
  USE_CC: False


MODEL:
  # GENERAL
  USE_TWO_HEADS: True
  NUM_LAYERS: 4
  HIDDEN_CHANNELS: 1024
  DROPOUT: 0.0
  # ENCODINGS
  USE_SIREN: False
  USE_WIRE_REAL: False
  USE_FF: True

FOURIER:
  MAPPING_SIZE: 256 # each per cos/sine
  FF_SCALE: 4.0
  FF_FACTOR: 1.0

SIREN:
  FIRST_OMEGA_0: 15
  HIDDEN_OMEGA_0: 15

WIRE:
  WIRE_REAL_FIRST_OMEGA_0: 15
  WIRE_REAL_HIDDEN_OMEGA_0: 15
  WIRE_REAL_FIRST_S_0: 15
  WIRE_REAL_HIDDEN_S_0: 15

MI_CC:
  LOSS_MI: 0.005
  GT_VAL: 0.471
  LOSS_CC: 0.0008
  MI_USE_PRED: False
  MI_NUM_BINS: 32  
  MI_SAMPLE_RATIO: 0.7
  NMI_SIGMA: 0.1

